# -*- coding: utf-8 -*-
"""Fine Tuning Bert For Sentiment Anaysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMpeGXj1f_5b3qLXC_c1PH_tovKdrZaE

**Imports**
"""


from datasets import DatasetDict,Dataset, load_dataset
from transformers import AutoTokenizer,AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate
import numpy as np
from transformers import DataCollatorWithPadding

"""**Load** **Data**"""

dataset= load_dataset("syedkhalid0/Sentiment-Analysis")

"""**Load Pre-trained Model**"""

model_path="bert-base-uncased"

#load model tokenizer
tokenizer= AutoTokenizer.from_pretrained(model_path)

#load model with binary classification head

model=AutoModelForSequenceClassification.from_pretrained(
    model_path,
    num_labels=3
    )

"""**Set Trainable Parameters**"""

#freeze all base model parameters
for name,param in model.base_model.named_parameters():
  param.requires_grad=False

#unfreeze base model pooling layers
for name,param in model.base_model.named_parameters():
  if "pooler" in name:
    param.requires_grad=True

"""**Data Pre-processing**"""

#define text preprocessing
def preprocess_function(example):
  return tokenizer(example["text"],truncation=True)

#preprocess all datasets
tokenized_data= dataset.map(preprocess_function,batched=True)

#create data collator
data_collator= DataCollatorWithPadding(tokenizer=tokenizer)

"""**Define Evaluation Metrix**"""

#load metrics
accuracy=evaluate.load("accuracy")
auc_score=evaluate.load("roc_auc")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    probabilities = np.exp(predictions) / np.exp(predictions).sum(-1, keepdims=True)
    auc = np.round(roc_auc_score(labels, probabilities, multi_class="ovr", average="macro"),3)

    predicted_classes = np.argmax(predictions, axis=1)
    acc = np.round(accuracy_score(labels, predicted_classes), 3)
    return {"accuracy": acc, "auc": auc}

"""**Training Parameters**"""

lr=2e-5
batch_size=16
num_epochs=3

training_args=TrainingArguments(
    output_dir="results",
    learning_rate=lr,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=num_epochs

    #logging_strategy="epoch",
    #eval_strategy="epoch",
    #save_strategy="epoch",
    #load_best_model_at_end=True

)

"""**Fine-tune Model**"""

trainer= Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_data["train"],
    eval_dataset=tokenized_data["validation"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.train()

eval_results = trainer.evaluate()
print(eval_results)

"""Labels:

0: Negative

1: Neutral

2: Positive
"""

from transformers import pipeline

model_id = "edaUsha/Fine_Tuning_Bert_For_Sentiment_Anaysis"

clf = pipeline(
    "text-classification",   # task
    model=model_id
)

print(clf("I really loved this movie!"))
print(clf("This was the worst experience ever.")))

